-- CreateEnum
CREATE TYPE "BudgetMode" AS ENUM ('FIXED', 'UNLIMITED', 'SELF_FUNDED');

-- AlterTable
ALTER TABLE "Participant" ADD COLUMN     "budget" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "budgetMode" "BudgetMode" NOT NULL DEFAULT 'FIXED',
ADD COLUMN     "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
