"use server";

import { prisma } from "@/lib/prisma";
import { createEventSchema } from "@/schemas/event.schema";
import { redirect } from "next/navigation";
import type { ActionResult } from "@/types";

export async function createEvent(
  data: unknown
): Promise<ActionResult<{ eventId: string }> | undefined> {
  const parsed = createEventSchema.safeParse(data);
  if (!parsed.success) {
    return { success: false, error: "Dữ liệu đầu vào không hợp lệ" };
  }

  let eventId: string;
  try {
    const newEvent = await prisma.event.create({
      data: {
        title: parsed.data.title,
        // ID is auto-generated by Prisma as UUID
        // Currency defaults to VND per schema
      },
      select: {
        id: true,
      },
    });
    eventId = newEvent.id;
  } catch (error) {
    console.error("[createEvent] error:", error);
    return { success: false, error: "Đã xảy ra lỗi khi tạo nhóm. Vui lòng thử lại." };
  }

  // Redirect outside try-catch because Next.js redirect() throws an error to work
  redirect(`/e/${eventId}`);
}

export async function getEventById(eventId: string) {
  try {
    const event = await prisma.event.findUnique({
      where: { id: eventId },
      select: {
        id: true,
        title: true,
        createdAt: true,
        currency: true,
        participants: {
          select: {
            id: true,
            name: true,
            deviceToken: true,
            paymentInfo: {
              select: {
                bankBIN: true,
                accountNumber: true,
                accountName: true,
                paypayLink: true,
              }
            }
          }
        },
        expenses: {
          orderBy: { createdAt: "desc" },
          select: {
            id: true,
            title: true,
            amount: true,
            payerId: true,
            createdAt: true,
            version: true,
            splits: {
              select: {
                participantId: true,
                amount: true,
              }
            }
          }
        }
      },
    });
    return event;
  } catch (error) {
    console.error("[getEventById] error:", error);
    return null;
  }
}
